baseURL = "https://ellingtonia.com/"
title = "Ellingtonia.com - A Duke Ellington Discography"
theme = "slick"
publishDir = "build"

copyright = "Ellingtonia.com"

canonifyURLs = true
preserveTaxonomyNames = true

disableKinds = ["RSS"]

ignoreLogs = ["warning-goldmark-raw-html"]

[permalinks]
  blog = "blog/:year/:filename/"

[params]
    # Site subtitle (not shown if commented out or set to false)
    subtitle = false

    # Site description
    description = "A Duke Ellington Discography"

    # Favicon file (relative to baseURL - place below static folder)
    favicon = "favicon.ico"

    # Custom css file (relative to baseURL - place below static folder)
    css = "css/style.css"

    dateFmt = "Mon, 02 Jan 2006 15:04:05 MST"

    errorPageText = "An error occurred"

    # Header with title/subtitle can be disabled here.
    # (If you disable this, add some link on the index page inside menu.main,
    #  otherwise your visitors will get confused and lost...)
    showNavHeader = true

    # Decide if only summaries are shown on the main page or the full content
    showFullContent = false

    # If false no pagination is shown when there is nothing to paginate
    showEmptyPagination = false

    # If false the title, dates and taxonomy are not shown on single view
    showMeta = true

    # If false the dates for the posts are not shown
    showMetaDates = false

    # If false the taxonomy links for the posts are not shown
    showMetaLinks = true

    # Uses Hugo internal templates if set
    opengraph = false
    schema = false
    twitter_cards = false

    # This prevents discog pages appearing on the front page
    mainSections = ["blog"]

[[params.entry_links]]
    description = "Discogs.com"
    key = "discogs"
    text = "(D)"

[[params.entry_links]]
    description = "MusicBrainz.org"
    key = "musicbrainz"
    text = "(MB)"

[[params.entry_links]]
    description = "Amazon (US)"
    key = "amazon"
    text = "(A)"

[[params.entry_links]]
    description = "AllMusic"
    key = "allmusic"
    text = "(AM)"

[[params.entry_links]]
    description = "Archive.org"
    key = "archive"
    text = "(AR)"

[[params.entry_links]]
    description = "Misc file"
    key = "file"
    text = "(F)"

[[params.entry_links]]
    description = "Spotify"
    key = "spotify"
    text = "(S)"

[[params.entry_links]]
    description = "Tidal"
    key = "tidal"
    text = "(T)"

[[params.entry_links]]
    description = "YouTube"
    key = "youtube"
    text = "(YT)"

[[params.entry_links]]
    description = "Other"
    key = "other"
    text = "(O)"

# [author]
#     name = "Some Author"
#     email = "mail@example.org"
